{% set name = "pywwt" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4ae69bb1a54b8196da39d3afac9cf3f98272c03682cf162b2693649dc4a51707

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:

  host:
    - python >=3.7
    - setuptools
    - pip
    - nodejs

  run:
    # Keep alphabetized!
    - astropy >=1.0
    - beautifulsoup4
    - ipyevents
    - ipywidgets >=7.0
    - jupyterlab
    - lxml
    - matplotlib >=1.5
    - notebook
    - numpy >=1.9
    - pyqt
    - python >=3.7
    - python-dateutil
    - pytz
    - qtpy
    - reproject >=0.4
    - requests
    - tornado
    - traitlets
    - widgetsnbextension

test:
  imports:
    - pywwt
  requires:
    - xorg-libx11  # needed for Tk import on Azure CI

about:
  home: http://github.com/WorldWideTelescope/pywwt
  summary: AAS WorldWide Telescope in Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - pkgw
