{% set name = "pywwt" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4dc6e04cfbe04c6a7fe8d34c7c8d653783e81bd13adfef01445d7ae448ba64d6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:

  build:
    - python
    - setuptools
    - pip
    - nodejs

  run:
    - python
    - numpy >=1.9
    - matplotlib >=1.5
    - astropy >=1.0
    - requests
    - beautifulsoup4
    - python-dateutil
    - lxml
    - ipywidgets >=7.0
    - ipyevents
    - traitlets
    - pyqt
    - qtpy
    - flask
    - flask-cors
    - six
    - widgetsnbextension
    - jupyterlab
    - notebook
    - reproject >=0.4

test:
  imports:
    - pywwt

about:
  home: http://github.com/WorldWideTelescope/pywwt
  summary: WorldWideTelescope in Python
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - pkgw
