{% set name = "pywwt" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26fa3e7926387b123ae04ff2327d7e777bd7c8977bb8a0c516b04bdaf6cec5cb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - nodejs =14  # prevent unnecessary matrixing here

  host:
    - python >=3.7
    - setuptools
    - pip

  run:
    # Keep alphabetized!
    - astropy >=1.0
    - beautifulsoup4
    - ipyevents
    - ipywidgets >=7.0
    - jupyterlab
    - lxml
    - matplotlib >=1.5
    - notebook
    - numpy >=1.9
    - pyqt
    - python >=3.7
    - python-dateutil
    - pytz
    - qtpy
    - reproject >=0.8
    - requests
    - tornado
    - traitlets
    - widgetsnbextension

test:
  imports:
    - pywwt
  requires:
    - xorg-libx11  # needed for Tk import on Azure CI

about:
  home: http://github.com/WorldWideTelescope/pywwt
  summary: AAS WorldWide Telescope in Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
    - pkgw
