travis:
  secure:
    BINSTAR_TOKEN: FTQxGQS9ESdEA3pVrYqQL1/3yX/L+rMEpqR8Klq/M277BaAwui1KzPTH5Rt3Llwk3kqsRc9u1F/HtPCZuXN+mzfc5AuIotaoCNOYAUeghnla1lfxBVUl+ALftZ+H5zPHe4PZ85G1tSNBvm6/nTHlzMCMURHFFUzRl/j0Q+dlhgAnxfIaUKByrksj0Bj9K1dPIyOHzEQ9MFsD7TtqV15Y06fdfHxp5bvX6Q2N8KptUL7bSIZh8D2G1gvGAnvkP8Oq3VLZSZPg8ocg0P7Q6Mxyj4zMlDiwsIq6zKdsbpHnTpsSayGqCDRRmWKKjc8pzn91MDLy24rqxwvgvgXU36QkTtUQcjbj2PRpitHCg6qUyCNSuXp2DvLxZRQPdoV76RQBEJVTiUfJeg5271hIBLHlo0ZPmgPF5V22eOoC2lIuhvu49ffBt2Dtx8PACp/ha9K9nkLZ8NqNFaR0rEy5oFOYYNaSAtMabTBbFj6v2yWecJS9cRPAKqrWwcVJbyyGNWf4MeobH1Tq14maATLvNm+fg6lQwdar4EM1SDs17FbQuBOnvoa9sJxbkLBOM/x0grPAE5riKFAZxcC3vimgtkXVlkW+1VVt8iBtcpQA2mR3JGkppFf0HDm1sz3XH1ER0uvHSUByG6xYKeEOdXsM2FSzOSEgpJPOtqtMjwODVfNaWV4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
